name: checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./backend/target
      - name: Check
        run: cargo check --release

  check-ethereum:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ethereum
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.15.0"
      - name: Cache
        uses: actions/cache@v2
        with:
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-
          path: ~/.npm
      - name: Install
        run: npm install
      - name: Lock
        run: bash -c '[[ -z $(git status --short --porcelain) ]] || exit 1'
      - name: Test
        run: npm test
